# from: https://github.com/GoogleCloudPlatform/golang-samples/blob/main/run/helloworld/Dockerfile
FROM golang:1.17.5-buster as builder

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . ./

RUN go build -v -o server ./cmd/web
RUN go build -v -o simpurl ./cmd/cli

FROM debian:buster-slim
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/server /app/server
COPY --from=builder /app/simpurl /app/simpurl

COPY ./web /web

ARG config_file 
ENV CONFIG_FILE=${config_file}
COPY ./${config_file} .

CMD ["/app/server"]