name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker compose up -d --build
      - name: DB check connection
        run: docker compose run server ping -c 5 db
      - name: Test
        run: docker compose run server go test ./... -count=1
      - name: Cleanup
        run: docker compose down